---
- name: Despliegue de Aplicacion Web y P치gina Web
  hosts: all
  become: true
  vars_files:
    - vars/variables.yml

  tasks:
    - name: Instalar prerrequisitos
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

  #Configuracion de Apache
    - name: Instalar servicios
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]

    - name: Crear ruta de despliegue Aplicaci칩n web
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Configurar virtualhost de apache
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: Establecer el sitio web
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Deshabilitar el sitio de apache por default
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

  # Configuracion de MySQL
    - name: Establecer contrase침a para el usuario root de MySQL
      ignore_errors: yes
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Remover todos los usuarios anonimos de MySQL
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Remover la base de datos test de MySQL
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

  # Cargamos la base de datos al servidor
    - name: Crear la base de datos
      mysql_db: name=Hospital state=present login_user=root login_password="456"

    - name: Copiar el esquema de la Base de Datos
      copy: src=files/db.sql dest=/tmp/db.sql

    - name: Ejecutar el script de la Base de Datos
      ignore_errors: yes
      mysql_db: name=Hospital state=import target=/tmp/db.sql login_user=root login_password="456"


  # Configuracion del Firewall
    - name: "UFW - Permitir HTTP en el puerto {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  #Aplicaci칩n web
    - name: Clonar App Web
      copy:
        src: "web/app/"
        dest: "/var/www/{{ http_host }}/"
       
  # PHP Info Page
    - name: Sets Up PHP Info Page
      template:
        src: "files/info.php.j2"
        dest: "/var/www/{{ http_host }}/info.php"

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
